[build-system]
requires = ["setuptools>=64.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "enflow"
version = "0.0.2"
description = "⚡ Open-source framework for sequential decision problems in the energy domain"
authors = [
    { name = "rebase.energy", email = "hello@rebase.energy" }
]
license = { text = "MIT" }
urls = { "Homepage" = "https://github.com/rebase-energy/enflow" }
dependencies = [
    "pandas",
    "pytz",
    "energydatamodel",
    "gymnasium"
]
